[package]
name = "prost_test"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bytes = "1.6"
prost = "0.12.4"

[build-dependencies]
prost-build = "0.12.4"

