icons_format = "{icon}"

[theme]
theme = "ctp-macchiato"

[icons]
icons = "material-nf"

[[block]]
block = "sound"
[[block.click]]
button = "left"
cmd = "pavucontrol"

[[block]]
block = "battery"
format = " $icon $percentage "
device = "DisplayDevice"
driver = "upower"

[[block]]
block = "bluetooth"
mac = "FD:63:B6:0D:6D:35"
disconnected_format = ""
format = " $icon "
[block.battery_state]
"0..20" = "critical"
"21..70" = "warning"
"71..100" = "good"
[[block.click]]
button = "left"
cmd = "blueman-manager"

[[block]]
block = "bluetooth"
mac = "F4:B6:2D:BA:FA:45"
disconnected_format = ""
format = " $icon "
[block.battery_state]
"0..20" = "critical"
"21..70" = "warning"
"71..100" = "good"
[[block.click]]
button = "left"
cmd = "blueman-manager"

[[block]]
block = "net"
format = " $icon"

[[block]]
block = "disk_space"
path = "/"
info_type = "available"
alert_unit = "GB"
interval = 20
warning = 20.0
alert = 10.0
format = " $icon $available.eng(w:2) "

[[block]]
block = "temperature"
format = " $icon $average "
interval = 10
chip = "*-isa-*"


[[block]]
block = "cpu"
info_cpu = 20
warning_cpu = 50
critical_cpu = 90

[[block]]
block = "memory"
format = " $icon $mem_total_used_percents.eng(w:2) "
format_alt = " $icon_swap $swap_used_percents.eng(w:2) "

[[block]]
block = "time"
interval = 5
format = " $timestamp.datetime(f:'%a %d/%m %R') "
