# Don't print a new line at the start of the prompt
add_newline = false

# Make prompt a single line instead of two lines
#[line_break]
#disabled = false

# Replace the "❯" symbol in the prompt with "➜"
# [character]                         # The name of the module we are configuring is "character"
# success_symbol = "[➜](bold green)"  # The "success_symbol" is set to "➜" with color "bold green"

# Use custom format
# format = """
# [┌───────────────────>](bold green)
# [│](bold green)$directory$rust$package
# [└─>](bold green) """

command_timeout = 5000

# Disable the package module, hiding it from the prompt completely
[package]
disabled = true

[cmd_duration]
disabled = true

palette = "catppuccin_macchiato"

[palettes.catppuccin_macchiato]
rosewater = "#f4dbd6"
flamingo = "#f0c6c6"
pink = "#f5bde6"
mauve = "#c6a0f6"
red = "#ed8796"
maroon = "#ee99a0"
peach = "#f5a97f"
yellow = "#eed49f"
green = "#a6da95"
teal = "#8bd5ca"
sky = "#91d7e3"
sapphire = "#7dc4e4"
blue = "#8aadf4"
lavender = "#b7bdf8"
text = "#cad3f5"
subtext1 = "#b8c0e0"
subtext0 = "#a5adcb"
overlay2 = "#939ab7"
overlay1 = "#8087a2"
overlay0 = "#6e738d"
surface2 = "#5b6078"
surface1 = "#494d64"
surface0 = "#363a4f"
base = "#24273a"
mantle = "#1e2030"
crust = "#181926"

##OneDark
#[character]
#success_symbol = "[❯](bold #61afef)"
#error_symbol = "[❯](bold #e86671)"
#vimcmd_symbol = "[❮](bold #98c379)"
#vimcmd_replace_one_symbol = "[❮](bold #e86671)"
#vimcmd_replace_symbol = "[❮](bold #e86671)"
#vimcmd_visual_symbol = "[❮](bold #c678dd)"
#
#[directory]
#truncation_length = 20
#style = "bold #61afef"
#
#[git_branch]
#symbol = " "
#style = "bold #e5c07b"
#
#[git_status]
#style = "bold #e86671"


##Dracula
#[character]
#success_symbol = "[❯](bold #50fa7b)"
#error_symbol = "[❯](bold #ff5555)"
#vimcmd_symbol = "[❮](bold #bd93f9)"
#vimcmd_replace_one_symbol = "[❮](bold #ff5555)"
#vimcmd_replace_symbol = "[❮](bold #ff5555)"
#vimcmd_visual_symbol = "[❮](bold #f1fa8c)"
#
#[directory]
#truncation_length = 20
#style = "bold #bd93f9"
#
#[git_branch]
#symbol = " "
#style = "bold #ff79c6"
#
#[git_status]
#style = "bold #ff5555"

##DoomOne
#[character]
#success_symbol = "[❯](bold #98be65)"
#error_symbol = "[❯](bold #ff6c6b)"
#vimcmd_symbol = "[❮](bold #51afef)"
#vimcmd_replace_one_symbol = "[❮](bold #ff6c6b)"
#vimcmd_replace_symbol = "[❮](bold #ff6c6b)"
#vimcmd_visual_symbol = "[❮](bold #a9a1e1)"
#
#[directory]
#truncation_length = 20
#style = "bold #51afef"
#
#[git_branch]
#symbol = " "
#style = "bold #da8548"
#
#[git_status]
#style = "bold #ff6c6b"
