# alevtd
# Autogenerated from man page /usr/lib/jvm/default/man/man1/alevtd.1.gz
complete -c alevtd -s h -d 'print a short help text and the default values for all options'
complete -c alevtd -s v -d 'set vbi device (default: /dev/vbi0)'
complete -c alevtd -s d -d 'enable debug output'
complete -c alevtd -s s -d 'Write a start/stop notice and serious errors to the syslog'
complete -c alevtd -s t -d 'set network timeout to >sec< seconds'
complete -c alevtd -s c -d 'set the number of allowed parallel connections to >n<'
complete -c alevtd -s p -d 'listen on port >port< for incoming connections.   Default 5654'
complete -c alevtd -s n -d 'set the hostname which the server should use (required for redirects)'
complete -c alevtd -s i -d 'bind to IP-address >ip<'
complete -c alevtd -s l -d 'log all requests to the logfile >log< (common log format)'
complete -c alevtd -s L -d 'same as above, but additional flush every line'
complete -c alevtd -s u -d 'set uid to >user< (after binding to the tcp port)'
complete -c alevtd -s g -d 'set gid to >group< (after binding to the tcp port)'
complete -c alevtd -s F -d 'don\'t run as daemon'
complete -c alevtd -s r -d 'poll tv frequency, clear vtx page cache if a frequency change was detected'

