# dfu-suffix
# Autogenerated from man page /usr/lib/jvm/default/man/man1/dfu-suffix.1.gz
complete -c dfu-suffix -s v -l vid -d 'Specify USB vendor ID (hexadecimal)'
complete -c dfu-suffix -s p -l pid -d 'Specify USB product ID (hexadecimal)'
complete -c dfu-suffix -s d -l did -d 'Specify USB device ID (hexadecimal)'
complete -c dfu-suffix -s S -l spec -d 'Specify DFU specification version (hexadecimal)'
complete -c dfu-suffix -s h -l help -d 'Displays a help message'
complete -c dfu-suffix -s V -l version -d 'Displays the software version.  EXAMPLES'
complete -c dfu-suffix -o 64 -d 'Usage error LIMITATIONS'

