# dfu-prefix
# Autogenerated from man page /usr/lib/jvm/default/man/man1/dfu-prefix.1.gz
complete -c dfu-prefix -s s -l stellaris-address -d '(in combination with --add) Add TI Stellaris address prefix to file'
complete -c dfu-prefix -s T -l stellaris -d '(in combination with --delete or --check) Act on TI Stellaris address prefix …'
complete -c dfu-prefix -s L -l lpc-prefix -d '(in combination with --add or --delete or --check) Use NXP LPC DFU prefix for…'
complete -c dfu-prefix -s h -l help -d 'Displays a help message'
complete -c dfu-prefix -s V -l version -d 'Displays the software version.  EXAMPLES'
complete -c dfu-prefix -o 64 -d 'Usage error'

