# dfu-programmer
# Autogenerated from man page /usr/lib/jvm/default/man/man1/dfu-programmer.1.gz
complete -c dfu-programmer -l force
complete -c dfu-programmer -l serial -d 'sequence of bytes into the memory image programmed into the device'
complete -c dfu-programmer -l quiet
complete -c dfu-programmer -l debug -d 'Configure Registers The standard bootloader for 8051 based chips supports wri…'

