# fbtv
# Autogenerated from man page /usr/lib/jvm/default/man/man1/fbtv.1.gz
complete -c fbtv -s h -d 'Display a command line options summary'
complete -c fbtv -s o -d 'set base string for the snapshot output files'
complete -c fbtv -s v -d 'Be verbose'
complete -c fbtv -s c -d 'video4linux device (default is /dev/video0)'
complete -c fbtv -s D -d 'video4linux driver (default is libv4l)'
complete -c fbtv -s d -d 'framebuffer device (default is $FRAMEBUFFER; /dev/fb0 if unset)'
complete -c fbtv -s g -d 'grayscaled display (works for 256 color mode only)'
complete -c fbtv -s s -d 'sets the V4L2 capture in width x height resolution if possible'
complete -c fbtv -s f -d 'font for text.   Default is to look for lat1-16 console font'
complete -c fbtv -s m -d 'video mode for TV.   fbtv will look up the mode in /etc/fb. modes'
complete -c fbtv -s j -d 'joystick device to use for controlling fbtv'
complete -c fbtv -s k -d 'keep capture on when switching consoles'
complete -c fbtv -s q -d 'quiet mode'
complete -c fbtv -s M -d 'EXPERIMENTAL: Turn on backend scaler mode (write yuv to offscreen memory and …'

