# fontmatrix
# Autogenerated from man page /usr/share/man/man1/fontmatrix.1.gz
complete -c fontmatrix -o la -l langs-available -d 'Print a list of languages for which user interface translations are available'
complete -c fontmatrix -o ns -l no-splash -d 'Suppresses display of the splash screen during SCribus start-up'

