# mtt
# Autogenerated from man page /usr/lib/jvm/default/man/man1/mtt.1.gz
complete -c mtt -o help -d 'print help text'
complete -c mtt -o debug -d 'enable debug messages'
complete -c mtt -o device -d 'vbi device (default is /dev/vbi0)'
complete -c mtt -o tty -d 'force using the console mode'

