# pia
# Autogenerated from man page /usr/lib/jvm/default/man/man1/pia.1.gz
complete -c pia -s h -d 'display help text'
complete -c pia -s v -d 'be verbose'
complete -c pia -o debug -d 'enable debug messages'
complete -c pia -o dsp -d 'Use OSS device <dev> for sound'
complete -c pia -o noxv -d 'Disable Xvideo extension'
complete -c pia -o nogl -d 'Disable OpenGL'
complete -c pia -o noaudio -d 'Don\'t play sound'
complete -c pia -o novideo -d 'Don\'t play video'
complete -c pia -o slow -d 'Slowdown video playback by factor n.   n=2 doubles playback time, '

