# propwatch
# Autogenerated from man page /usr/lib/jvm/default/man/man1/propwatch.1.gz
complete -c propwatch -o watch -d 'Display to monitor the windows on'
complete -c propwatch -o verbose -d 'be verbose'
complete -c propwatch -o proplog -d 'Log property changes to stdout'
complete -c propwatch -o display -o geometry
complete -c propwatch -o kbdlog -d 'Log keystrokes to stdout'

