# radio
# Autogenerated from man page /usr/lib/jvm/default/man/man1/radio.1.gz
complete -c radio -s h -d 'print a short help text'
complete -c radio -s d -d 'enable debug output'
complete -c radio -s q -d 'quit after processing the cmd line options, don\'t enter interactive ncurses m…'
complete -c radio -s m -d 'mute radio'
complete -c radio -s f -d 'tune the specified radio frequency (and unmute the radio)'
complete -c radio -s c -d 'specify radio device (default is /dev/radio0)'
complete -c radio -s s -d 'Do a scan for radio stations'
complete -c radio -s S -d 'Same as above + write a radio. fmmap with the signal for every frequency'
complete -c radio -s i -d 'Scan, write a initial ~/. radio file to stdout and quit'

