# record
# Autogenerated from man page /usr/lib/jvm/default/man/man1/record.1.gz
complete -c record -s h -d 'display help text'
complete -c record -s o -d 'basename for the output file(s), a number and the '
complete -c record -s i -d 'mixer control'
complete -c record -s m -d 'set mixer device.   Default is "/dev/mixer"'
complete -c record -s d -d 'set audio device.   Default is "/dev/dsp"'
complete -c record -s r -d 'set sample rate.   Default is 44100'
complete -c record -s p -d 'peak seconds (number of seconds which should be scanned for the volume maximu…'
complete -c record -s c -d 'enable console (non-interactive) mode'
complete -c record -s v -d 'be verbose (console mode only)'
complete -c record -s t -d 'Limit the record time (console mode only)'
complete -c record -s s -d 'Limit the file size (console mode only)'
complete -c record -s n -d 'Limit the file count (console mode only)'
complete -c record -s l -d 'Enable level triggered recording (console mode only) with the default trigger…'
complete -c record -s L -d 'Enable level triggered recording with the specified trigger level'

