# rootv
# Autogenerated from man page /usr/lib/jvm/default/man/man1/rootv.1.gz
complete -c rootv -o help -d 'Print a short description of all command line options'
complete -c rootv -o verbose -d 'Be verbose.   That will dump some debug messages to stderr'
complete -c rootv -o root -d 'Put the video onto the root window instead of creating a new window'
complete -c rootv -o id -d 'Put the video into the window <win> instead of creating a new window'
complete -c rootv -o station -d 'Tune station <st>'
complete -c rootv -o no-mute -d 'Don\'t toggle mute'
complete -c rootv -o port -d 'Use Xvideo port <n>'
complete -c rootv -o bg -d 'Fork into background'
complete -c rootv -o wm -d 'Print WindowMaker menu (set stations using v4lctl)'

