# scantv
# Autogenerated from man page /usr/lib/jvm/default/man/man1/scantv.1.gz
complete -c scantv -s i -d 'set tv  input (Television/Composite1/S-video and so on)'
complete -c scantv -s n -d 'set tv  norm.    scantv will ask interactively if none is given'
complete -c scantv -s f -d 'set frequency table.   scantv will ask interactively if none is given'
complete -c scantv -s o -d 'specify output file.   If none is specified, scantv writes to stdout'
complete -c scantv -s c -d 'specify video device file.   Default is /dev/video0'
complete -c scantv -s D -d 'specify video driver name.   Default is "libv4l"'
complete -c scantv -s C -d 'specify vbi device file.   Default is /dev/vbi0'
complete -c scantv -s s -d 'skip channel scan, just write norm + freqtab to the config file'
complete -c scantv -s a -d 'Do a full scan (i. e'

