# showriff
# Autogenerated from man page /usr/lib/jvm/default/man/man1/showriff.1.gz
complete -c showriff -s h -d 'display help text'
complete -c showriff -s j -d 'try to decode mjpeg headers'
complete -c showriff -s e -d 'try to continue on errors.  SEE ALSO c\'t 11/1994, page 327 ff'

