# subtitles
# Autogenerated from man page /usr/lib/jvm/default/man/man1/subtitles.1.gz
complete -c subtitles -o help -d 'print a short help text'
complete -c subtitles -o tty -d 'dump a copy of the videotext page to the tty'

