# tabbed
# Autogenerated from man page /usr/local/man/man1/tabbed.1
complete -c tabbed -s k -d 'close foreground tabbed client (instead of tabbed and all clients) when WM_DE…'
complete -c tabbed -s o -d 'defines the normal background color. RI # RGB , '
complete -c tabbed -s O -d 'defines the normal foreground color'

