# ttv
# Autogenerated from man page /usr/lib/jvm/default/man/man1/ttv.1.gz
complete -c ttv -s h -d 'print help text'
complete -c ttv -s f -d 'use fast aalib render function'
complete -c ttv -s c -d 'video4linux device (default is /dev/video0)'
complete -c ttv -s D -d 'video4linux driver (default is "libv4l")'

