# v4l-conf
# Autogenerated from man page /usr/lib/jvm/default/man/man8/v4l-conf.8.gz
complete -c v4l-conf -s h -d 'Print a short description of all command line options'
complete -c v4l-conf -s q -d 'Be quiet'
complete -c v4l-conf -s d -d 'Use the X11 display dpy to get the parameters'
complete -c v4l-conf -s f -d 'Use the framebuffer driver to get the parameters'
complete -c v4l-conf -s c -d 'Set the video4linux device'
complete -c v4l-conf -s b -d 'enforce  n bpp color depth.   Works for switching between 15/16 and 24/32 bpp'
complete -c v4l-conf -s s -d 'Shift the video display by  n bytes'
complete -c v4l-conf -s a -d 'Set framebuffer address to adr.   The value should be specified in hex'
complete -c v4l-conf -s p -d 'Set framebuffer pitch to pitch bytes'

