# xawtv-remote
# Autogenerated from man page /usr/lib/jvm/default/man/man1/xawtv-remote.1.gz
complete -c xawtv-remote -s h -d 'print a short help text'
complete -c xawtv-remote -s d -d 'Set the X11 display'
complete -c xawtv-remote -s i -d 'Set the Window ID. P  v4lctl understands these options:'
complete -c xawtv-remote -s c -d 'Set video4linux device'
complete -c xawtv-remote -s D -d 'Set video4linux driver'
complete -c xawtv-remote -s v -d 'Set debug level to n, where n = [0'

